name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog:latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code test 1111
        run: |
          rm -rf /__w/trufflehogtest/trufflehogtest/.git
          trufflehog filesystem /__w/trufflehogtest/trufflehogtest --no-verification --no-update
          echo "::set-output name=status::$?"
      - name: send msg
        run: |
          if [ "${{ steps.step1.outputs.status }}" -eq 183 ]; then
            echo "Previous command failed with exit code 183  11111"
          fi