name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog:latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code test 1111
        run: |
          ls -alR /__w/trufflehogtest/
          rm -rf /__w/trufflehogtest/trufflehogtest/.git
          trufflehog filesystem /__w/trufflehogtest/trufflehogtest --no-verification --no-update