name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog:latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout code test 1111
        id: mystep
        continue-on-error: true
        run: |
          mystring="${{ github.workspace }}"
          echo ${mystring:18}
          rm -rf /__w/${mystring:18}/.git
          trufflehog filesystem /__w/${mystring:18} --no-verification --no-update --fail
      - name: send msg
        if: ${{steps.mystep.outcome == 'failure'}}
        run: |
          echo "error   876868767878608760876"
      - name: test
        run: |
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"