name: TruffleHog Secrets Scan
on: [push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    container:
      image: trufflesecurity/trufflehog:latest
    steps:
      - uses: actions/checkout@v4
      - name: scan code
        id: scancode
        continue-on-error: true
        run: |
          echo "--------------------------------------"
          /usr/bin/git config --global -l
          echo "`/usr/bin/git config --global --get safe.directory`"
